"""Core runtime package for SAPHive."""

from saphive.core.com import ComRuntime
from saphive.core.config import (
    LoggingConfig,
    PathsConfig,
    RuntimeConfig,
    SapCleanupMode,
    SapConfig,
    SapConnectionMode,
    SapConnectionProfile,
    SAPHiveConfig,
    default_cli_config_dir,
    find_cli_config,
    find_default_config,
    load_config,
    load_default_config,
)
from saphive.core.context import RuntimePaths, SapContext, build_sap_context
from saphive.core.errors import (
    AutomationError,
    BotContractError,
    BusinessAutomationError,
    ComRuntimeError,
    ConfigurationError,
    ExcelInfrastructureError,
    FatalAutomationError,
    InfrastructureError,
    SAPAutomationError,
    SapConnectionError,
    SapGuiError,
    SAPHiveError,
    SapInfrastructureError,
    SapSessionError,
    ScriptDiscoveryError,
    ScriptExecutionError,
    ScriptLoadError,
    ScriptValidationError,
)
from saphive.core.results import ExecutionStatus, ScriptExecutionResult
from saphive.core.runtime import SapRuntime
from saphive.sap.interfaces import SapGuiPlaceholder

__all__ = [
    "AutomationError",
    "BotContractError",
    "BusinessAutomationError",
    "ComRuntime",
    "ComRuntimeError",
    "ConfigurationError",
    "ExcelInfrastructureError",
    "ExecutionStatus",
    "FatalAutomationError",
    "InfrastructureError",
    "LoggingConfig",
    "PathsConfig",
    "RuntimeConfig",
    "RuntimePaths",
    "SAPAutomationError",
    "SAPHiveConfig",
    "SAPHiveError",
    "SapCleanupMode",
    "SapConfig",
    "SapConnectionError",
    "SapConnectionMode",
    "SapConnectionProfile",
    "SapContext",
    "SapGuiError",
    "SapGuiPlaceholder",
    "SapInfrastructureError",
    "SapRuntime",
    "SapSessionError",
    "ScriptDiscoveryError",
    "ScriptExecutionError",
    "ScriptExecutionResult",
    "ScriptLoadError",
    "ScriptValidationError",
    "build_sap_context",
    "default_cli_config_dir",
    "find_cli_config",
    "find_default_config",
    "load_config",
    "load_default_config",
]
